bookers/config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :books
  #resources :books#, only:[:index]
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    # 4. トップ画面へリダイレクト
    else
      @books = Book.all
      render 'books/index'
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def top
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book= Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy
    flash[:success2] = 'Book was successfully destroyed.'# データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1 class='h12'>Editing Book</h1>
<% if @book.errors.any? %>
  <div class='error'>
    <h2 class='errorh2'>
      <%= @book.errors.count %> error prohibited this book from being saved:
    </h2>
    <ul class='errorul'>
      <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @book do |f| %>
 <div class='index-newbook'>
  <p>Title</p>
  <%= f.text_field :title %>
 </div>
 <div class='index-newbook'>
  <p>Body</p>
  <%= f.text_area :body %>
 </div>
 <div class='index-newbook'>
  <%= f.submit 'Update Book' %>
 </div>
 <%= link_to "Show", book_path(@book.id) %>
     |
 <%= link_to 'Back', '/books' %>
<% end %>

bookers/app/views/books/index.html.erb
    <p id='notice'>
        <%= flash[:success2] %>
    </p>
    <h1 class='h12'>Books</h1>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Body</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
              <%  @books.each do |book| %>
                <tr>
                    <td><%= book.title %></td>
                    <td><%= book.body %></td>
                    <td>
                        <p class='index-a'>
                            <%= link_to "Show",book_path(book.id) %>
                        </p>
                    </td>
                    <td>
                        <p class='index-a'>
                            <%= link_to "Edit", edit_book_path(book.id) %>
                        </p>
                    </td>
                    <td>
                        <p class='index-a'>
                             <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
                        </p>
                    </td>
                </tr>
              <% end %>

        </tbody>
    </table>
    <h2 class='h12'>New book</h2>
    <!--url: '/books', method: :post-->
    <% if @book.errors.any? %>
      <div class='error'>
        <h2 class='errorh2'>
          <%= @book.errors.count %> error prohibited this book from being saved:
        </h2>
        <ul class='errorul'>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @book do |f|  %>
    <div class='index-newbook'>
      <p>Title</p>
      <%= f.text_field :title %>
    </div>
    <div class='index-newbook'>
      <p>Body</p>
      <%= f.text_area :body %>
    </div>
    <div class='index-newbook'>
      <%= f.submit 'Create Book' %>
    </div>
    <% end %>

bookers/app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

bookers/app/views/books/show.html.erb
<p id='notice'>
    <%= flash[:success] %>
</p>
<p class='box'>
    <straong>Titel:</straong>
    <%= @book.title %>
</p>

<p class='box'>
    <straong>Body:</straong>
    <%= @book.body %>

</p>

<div>
     <%= link_to "Edit", edit_book_path(@book.id) %>
     |
     <%= link_to 'Back', '/books' %>

</div>

bookers/app/views/homes/top.html.erb
<div class='top-page'>
    <h1>ようこそ <strong>Bookers</strong>へ!</h1>
    <div class='box'>
        <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
    </div>
    <div class='box'>
        <p>印象を共有し交換することができます</p>
    </div>
    <div class='box'>
        <p class="nav-list-item">
        <%= link_to "start", '/books' %>
        </p>
    </div>
</div>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>